# ============================================
# DATABASE
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/taptrack_db
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ============================================
# LOGGING CONTROL
# ============================================
logging.level.com.tuan.course_management=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN