spring.application.name=TapTrack
server.port=8080

# Kích hoạt đồng thời dev và local
spring.profiles.active=dev,local

#jwt.secret=${JWT_SECRET:my-default-dev-secret-key-at-least-256-bits-long}
jwt.expiration=86400000
jwt.refresh-expiration=604800000