spring.application.name=TapTrack
server.port=8080

# Kích hoạt đồng thời dev và local
spring.profiles.active=dev,local

# Cấu hình Jackson JSON (Format thời gian ISO-8601 chuẩn)
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Ho_Chi_Minh